### ISSUE TITLE
Search problem in sct-browser-frontend versjon 3.37.0

### ISSUE THREAD

**Issue by drbarbero** [IHTSDO/sct-browser-frontend#82]
We have a problem with search in the browser.
When we search for e.g. "angst" we do not get any results, but if we type "angst a" we get results (see attachment).

Can you point us in the right direction on how to fix this?

sct-browser-frontend versjon 3.37.0
Snowstorm versjon 8.3.0

<img width="617" alt="Screenshot 2023-11-09 at 13 11 15" src="https://github.com/IHTSDO/sct-browser-frontend/assets/74706024/4f2f29ab-0c52-4319-bc17-c14a7cd195df">
<img width="413" alt="Screenshot 2023-11-09 at 13 10 26" src="https://github.com/IHTSDO/sct-browser-frontend/assets/74706024/275e8a95-73aa-41b9-99e9-1becc925ef1a">

<img width="598" alt="Screenshot 2023-11-09 at 13 11 06" src="https://github.com/IHTSDO/sct-browser-frontend/assets/74706024/5fe31983-72ce-4715-b414-375415baded5">
<img width="409" alt="Screenshot 2023-11-09 at 13 10 55" src="https://github.com/IHTSDO/sct-browser-frontend/assets/74706024/8324313b-6bdc-4633-80ca-7615a4d7f914">

**Comment by kaicode** [comment]
This is related to a new feature where concepts can be found using alternative identifiers, which will be used in the SNOMED LOINC extension. It seems that the first search fails because it attempts an alternate identifier lookup that Snowstorm 8.3.0 does not yet support. The second search contains a space so the frontend does not attempt an alternate identifier lookup.

@Chris-Swires Am I correct here? Could you suggest the best version of the browser frontend to use with Snowstorm 8.3.0 please?

**Comment by drbarbero** [comment]
Thanks @kaicode.
@Chris-Swires Could you please suggest to us the best version of the browser frontend to use with Snowstorm 8.3.0.

**Comment by Chris-Swires** [comment]
Hey @drbarbero - 3.32.0 is the last pre alternative identifiers release, in hindsight perhaps we should have versioned 3.33.0 as 4.0.0.

**Comment by drbarbero** [comment]
Thanks @Chris-Swires, it works with versjon 3.32.0
